name: CI/CD Pipeline
on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: project/package-lock.json

      - name: Install dependencies
        working-directory: ./project
        run: npm ci

      - name: Run ESLint
        working-directory: ./project
        run: npm run lint

      - name: Run TypeScript type check
        working-directory: ./project
        run: npm run typecheck

  build:
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: project/package-lock.json

      - name: Install dependencies
        working-directory: ./project
        run: npm ci

      - name: Build project
        working-directory: ./project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: project/dist
          retention-days: 7
